[package]
name = "thunder-ui-gtk"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.8"
gio = "0.19"
glib = "0.19"
log = "0.4"
env_logger = "0.11"

thunder-core = { path = "../thunder-core" }
